name: "Build and test JavaScript bindings"

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  build:
    name: Build and test JavaScript bindings
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - run: |
       sudo apt install -y libsodium-dev nodejs pkgconf python3-pip uncrustify # build-essential git
       # liboprf
       git clone https://github.com/stef/liboprf/
       cd js
       git clone https://github.com/emscripten-core/emsdk.git # https://emscripten.org/docs/getting_started/downloads.html
       cd emsdk
       ./emsdk install 1.40.1
       ./emsdk activate 1.40.1
       source ./emsdk_env.sh
       cd ..
       make LIBOPRFHOME=../liboprf/src
       echo emsdk >.prettierignore
       echo libsodium.js >>.prettierignore
       make LIBOPRFHOME=../liboprf/src format es-check test
